### PR TITLE
Am branch

### PR DESCRIPTION
**Pull request by amlyon**
@mgratti 

Importing the latest modifications to the master. 

The main developments are:
- NanoProdManager created: writes the status report of a bparking production and serves as a resubmitter
- NanoLauncher, NanoMerger and NanoProdManager now inherit from a common class NanoTools
- NanoDumper created as the ntuplising tool (initially written as a RDataFrame and then moved to a TSelector). For data, the luminosity mask is applied at this step
- The nano and dumping tools can be run independently following the instructions in the README
- Concerning the BParking code, fixed the unwanted selection in BToMuMuPiBuilder and BToKLLBuilder. The object selection is for the moment kept the same

I would like to the merging, and start working on the synchronisation with the latest version of the central code

### CODE REVIEW

**Comment by mgratti** [comment]
Hi @amlyon , congrats and thanks for the huge work! 
On my side, you can go ahead with the merging.

I only ask a couple of small questions 

For the json list, is it the same as the one linked here? https://twiki.cern.ch/twiki/bin/view/CMS/SUSRecommendationsRun2Legacy for 2018
i.e. https://cms-service-dqm.web.cern.ch/cms-service-dqm/CAF/certification/Collisions18/13TeV/ReReco/Cert_314472-325175_13TeV_17SeptEarlyReReco2018ABC_PromptEraD_Collisions18_JSON.txt 

Concerning the gen displacement information in the flattening step, I see that it's commented.. and was wondering why that is the case.

**Comment by amlyon** [comment]
Hi Maria Giulia, 

Thanks a lot for the comments! 

For the json list, yes, the file that you pointed is the file that I used. I also noticed recently that it is the json list pointed in the central BParkingNano code: https://github.com/CMSBParking/BParkingNANO/blob/master/BParkingNano/production/samples.yml#L3

Concerning the fact that gen displacement is commented, it is intentional, but it's good that you raise the remark. For the moment, the script would crash when run on data if the lines are uncommented, since it will try to access the GenPart_* branches, which exist only for MC (https://github.com/BParkHNLs/BParkingNANO/blob/am-branch/BParkingNano/plugins/dumper/NanoDumper.h#L306-L317). This will have to be addressed in a future version of the code by either:
* add BToMuMuPi branches with the gen displacement already in the nano samples
* instead of having a fixed NanoDumper, write the file at execution time, where we can choose to add/remove some lines depending of whether we run on MC or data (so something in the spirit of what is done in the HNLsGen prodHelper for the DEC files etc.)

All in all, I would like to avoid having a NanoDumperData and NanoDumperMC.

Any other idea is of course the welcome :)

**Comment by mgratti** [comment]
First proposed solution ok.

Second solution, seems complex and I am not sure that it can be implemented.

Alternative solution (not elegant, but effective without additional space on the nanoAODs)

As member of the class declare the branch but make it point to wrong existing branch in the tree:

`TTreeReaderArray<Float_t> GenPart_eta = {fReader, "Muon_eta"};`

In SlaveBegin() or Begin() method, reinitialise to point the correct branch:

`if (isMC) GenPart_eta  = {fReader, "GenPart_eta"};`

In process() access it only when it's MC:

`if(isMC) std::cout << "size gen=" <<  GenPart_eta.GetSize() << " size muon=" << Muon_eta.GetSize() << std::endl;`

I tried it in a tselector and it works correctly on MC. The size of the vector is correct and the value of accessed branch as well.
In data, if mistakenly used, these branches will give wrong information

**Comment by amlyon** [comment]
Thanks a lot for the suggestion, I'll try to implement something is this spirit!

**Pull request merged**
